# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('incumbent', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=120)),
                ('foundation', models.CharField(max_length=120)),
                ('inn', models.CharField(max_length=100)),
                ('kpp', models.CharField(max_length=100)),
                ('bik', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('kor_acc', models.CharField(max_length=100)),
                ('acc', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('legal_addr', models.CharField(max_length=150)),
                ('physic_addr', models.CharField(max_length=150)),
                ('contact_entity', models.CharField(max_length=150)),
                ('work_phone', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovernmentDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('incumbent', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=120)),
                ('foundation', models.CharField(max_length=120)),
                ('inn', models.CharField(max_length=100)),
                ('kpp', models.CharField(max_length=100)),
                ('bik', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('kor_acc', models.CharField(max_length=100)),
                ('acc', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('legal_addr', models.CharField(max_length=150)),
                ('physic_addr', models.CharField(max_length=150)),
                ('contact_entity', models.CharField(max_length=150)),
                ('work_phone', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('incumbent', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=120)),
                ('foundation', models.CharField(max_length=120)),
                ('inn', models.CharField(max_length=100)),
                ('kpp', models.CharField(max_length=100)),
                ('bik', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('kor_acc', models.CharField(max_length=100)),
                ('acc', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('legal_addr', models.CharField(max_length=150)),
                ('physic_addr', models.CharField(max_length=150)),
                ('contact_entity', models.CharField(max_length=150)),
                ('work_phone', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sur_name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(default='RU', max_length=2)),
                ('entity_type', models.CharField(choices=[('P', 'Физическое лицо'), ('L', 'Юридическое лицо'), ('E', 'Индивидуальный предпринематель'), ('G', 'Государственное учреждение')], default='P', max_length=1)),
                ('registered', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personalentity',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='governmentdepartment',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
